### ISSUE TITLE
Occasional segfaulting on close (ctrl-q) stock Ubuntu 16.04

### ISSUE THREAD

**Issue by glinton** [crmarsh/discord-linux-bugs#117]
While there appear to be no side-effects, I figured I'd report this. Occasionally, when I close discord I it will segfault.
```
$ discord-canary 
DiscordCanary 0.0.9
...
31376763: [+] Entered: Disconnect
31376763: [-] Exited: Disconnect
31476054: [+] Entered: Disconnect
31476054: [-] Exited: Disconnect
Segmentation fault (core dumped)
$
```

From `/var/crash/_usr_share_discord-canary_DiscordCanary.1000.crash`
```
Title: DiscordCanary crashed with SIGSEGV in webrtc::AudioDeviceLinuxPulse::PlayoutDevices()

Package: discord-canary 0.0.9 [origin: unknown]
PackageArchitecture: amd64
ProcVersionSignature: Ubuntu 4.4.0-45.66-generic 4.4.21

SegvAnalysis:
 Segfault happened at: 0x0:	Cannot access memory at address 0x0
 PC (0x00000000) not located in a known VMA region (needed executable region)!
 Stack memory exhausted (SP below stack segment)

SegvReason: executing NULL VMA

Stacktrace:
 #0  0x0000000000000000 in ?? ()
 No symbol table info available.
 #1  0x00007f79d30257e4 in webrtc::AudioDeviceLinuxPulse::PlayoutDevices() () from ~/.config/discordcanary/0.0.9/modules/discord_voice/libdiscord.so
 No symbol table info available.
 #2  0x00007f79d2fc2b4d in webrtc::AudioDeviceModuleImpl::PlayoutDevices() () from ~/.config/discordcanary/0.0.9/modules/discord_voice/libdiscord.so
 No symbol table info available.
 #3  0x00007f79d2f28fdf in DiscordInternal::AudioDevice::GetPlayoutDevices (devices=std::vector of length 2, capacity 2 = {...}) at ../../discord_native_lib/src/discord_audio_device.cpp:382
         numDevices = <optimized out>
 #4  0x00007f79d2f28aa6 in pollDevices () at ../../discord_native_lib/src/discord_audio_device.cpp:161
         sRecordingDevices = std::vector of length 2, capacity 2 = {{name = "Ua\b\276@\364\377\377U-\205\276@\364\377\377n Audio Analog Stereo", '\000' <repeats 90 times>, guid = '\000' <repeats 127 times>}, {name = "Built-in Audio Analog Stereo", '\000' <repeats 99 times>, guid = '\000' <repeats 127 times>}}
         sPlayoutDevices = std::vector of length 2, capacity 2 = {{name = "U\225J\276@\364\377\377Ue\356\275@\364\377\377n Audio Analog Stereo", '\000' <repeats 90 times>, guid = '\000' <repeats 127 times>}, {name = "Built-in Audio Analog Stereo", '\000' <repeats 99 times>, guid = '\000' <repeats 127 times>}}
 #5  0x00007f79d2f8c4d5 in uv__run_timers (loop=0xbbf41ec7408) at ../../discord_common/native/third_party/libuv/src/unix/timer.c:165
         heap_node = <optimized out>
 #6  0x00007f79d2f82604 in uv_run (loop=<optimized out>, mode=<optimized out>) at ../../discord_common/native/third_party/libuv/src/unix/core.c:345
         r = <optimized out>
 #7  0x00007f79d2f2c50f in DiscordInternal::EventLoop::WorkerThreadMain (this=<optimized out>) at ../../discord_native_lib/src/discord_event_loop.cpp:92
         pool = {mPool = 0x0}
 #8  0x00007f79ff653c80 in ?? () from /usr/lib/x86_64-linux-gnu/libstdc++.so.6
 No symbol table info available.
 #9  0x00007f7a0532b70a in start_thread (arg=0x7f79f221a700) at pthread_create.c:333
         __res = <optimized out>
         pd = 0x7f79f221a700
         now = <optimized out>
         unwind_buf = {cancel_jmp_buf = {{jmp_buf = {140161730062080, -8284700174972428055, 0, 140726477269999, 8388608, 12916065199232, 8355638933386092777, 8354985933635641577}, mask_was_saved = 0}}, priv = {pad = {0x0, 0x0, 0x0, 0x0}, data = {prev = 0x0, cleanup = 0x0, canceltype = 0}}}
         not_first_call = <optimized out>
         pagesize_m1 = <optimized out>
         sp = <optimized out>
         freesize = <optimized out>
         __PRETTY_FUNCTION__ = "start_thread"
 #10 0x00007f79fedb982d in clone () at ../sysdeps/unix/sysv/linux/x86_64/clone.S:109
 No locals.

Disassembly: => 0x0:	Cannot access memory at address 0x0
```

**Comment by crmarsh** [comment]
Well, easy fix: I'll disable closing :-)

Thanks for the report. Yeah, I was seeing that too, should be a simple fix...
