### ISSUE TITLE
Crash on load

### ISSUE THREAD

**Issue by Silvea12** [crmarsh/discord-linux-bugs#125]
Hey, so I just updated to 0.0.10 and this happened on load. I can't get into the software.

```js
Uncaught exception:
 Error: Object has been destroyed
    at Error (native)
    at SplashWindow.focus (/opt/discord-canary/resources/app.asar/SplashWindow.js:140:22)
    at /opt/discord-canary/resources/app.asar/index.js:634:22
    at Socket.<anonymous> (/opt/discord-canary/resources/app.asar/singleInstance.js:59:7)
    at emitOne (events.js:96:13)
    at Socket.emit (events.js:188:7)
    at readableAddChunk (_stream_readable.js:177:18)
    at Socket.Readable.push (_stream_readable.js:135:10)
    at Pipe.onread (net.js:542:20)
```

System details:
`Linux pikatop 4.8.6-1-ARCH #1 SMP PREEMPT Mon Oct 31 18:51:30 CET 2016 x86_64 GNU/Linux`
Arch Linux, 64-bit, default kernel. Installed from AUR.

**Comment by GhettoGirl** [comment]
I investigated this a bit, apperently deleting the file `/tmp/discordcanary.sock` when it exists fixes this problem. When it doesn't exist and still crashes I don't know what could be wrong then.

**Comment by ahjolinna** [comment]
same problem as: https://github.com/crmarsh/discord-linux-bugs/issues/122

**Comment by Silvea12** [comment]
Ah, thanks @GhettoGirl, solved the issue.
