### ISSUE TITLE
Javascript Object Error after .10 Update

### ISSUE THREAD

**Issue by PansFortress** [crmarsh/discord-linux-bugs#127]
Grabbed the .10 update and was thrown the following error on launch. 

`Uncaught exception:
 Error: Object has been destroyed
    at Error (native)
    at SplashWindow.focus (/usr/share/discord-canary/resources/app.asar/SplashWindow.js:140:22)
    at /usr/share/discord-canary/resources/app.asar/index.js:634:22
    at Socket.<anonymous> (/usr/share/discord-canary/resources/app.asar/singleInstance.js:59:7)
    at emitOne (events.js:96:13)
    at Socket.emit (events.js:188:7)
    at readableAddChunk (_stream_readable.js:177:18)
    at Socket.Readable.push (_stream_readable.js:135:10)
    at Pipe.onread (net.js:542:20)`

System Details: 
`Description:	elementary OS 0.4 Loki
Release:	0.4
Codename:	loki
Built on Ubuntu 16.04 LTS`

**Comment by PansFortress** [comment]
Closing as duplicate of https://github.com/crmarsh/discord-linux-bugs/issues/122
