### ISSUE TITLE
Unable to launch after 0.0.10-1 update

### ISSUE THREAD

**Issue by b1naryv1k1ng** [crmarsh/discord-linux-bugs#128]
Running Fedora 23, recently updated DiscordCanary through dnf. Repo being used is:

$ cat /etc/yum.repos.d/discord.repo 
[vishalv-discord-canary]
name=Copr repo for discord-canary owned by vishalv
baseurl=https://copr-be.cloud.fedoraproject.org/results/vishalv/discord-canary/fedora-$releasever-$basearch/
skip_if_unavailable=True
gpgcheck=1
gpgkey=https://copr-be.cloud.fedoraproject.org/results/vishalv/discord-canary/pubkey.gpg
enabled=1
enabled_metadata=1

When trying to launch Discord, I get the following error:

Uncaught exception:
 Error: Object has been destroyed
    at Error (native)
    at SplashWindow.focus (/opt/DiscordCanary/resources/app.asar/SplashWindow.js:140:22)
    at /opt/DiscordCanary/resources/app.asar/index.js:634:22
    at Socket.<anonymous> (/opt/DiscordCanary/resources/app.asar/singleInstance.js:59:7)
    at emitOne (events.js:96:13)
    at Socket.emit (events.js:188:7)
    at readableAddChunk (_stream_readable.js:177:18)
    at Socket.Readable.push (_stream_readable.js:135:10)
    at Pipe.onread (net.js:542:20)

**Comment by Dragory** [comment]
Getting this same error after the 0.0.11 update on Ubuntu 16.04, installing directly from .deb files:

    Uncaught exception:
     Error: Object has been destroyed
        at Error (native)
        at SplashWindow.focus (/usr/share/discord-canary/resources/app/SplashWindow.js:140:22)
        at /usr/share/discord-canary/resources/app/index.js:644:22
        at Socket.<anonymous> (/usr/share/discord-canary/resources/app/singleInstance.js:59:7)
        at emitOne (events.js:96:13)
        at Socket.emit (events.js:188:7)
        at readableAddChunk (_stream_readable.js:176:18)
        at Socket.Readable.push (_stream_readable.js:134:10)
        at Pipe.onread (net.js:543:20)

**Comment by Lerentis** [comment]
Same on arch linux with gnome 3.22.2
![screenshot from 2016-11-09 10-55-55](https://cloud.githubusercontent.com/assets/3034381/20134368/7cb2c87c-a66b-11e6-9647-017b1fa3e26a.png)

**Comment by ALFminecraft** [comment]
Same after updating to 0.0.11 on Arch Linux x64 from [https://aur.archlinux.org/packages/discord-canary/](AUR)
Tried to remove ~/.cache/discord, didn't help

**Comment by Lerentis** [comment]
ALFminecraft on the Linux dev channel suggested to run 
```
sudo killall DiscordCanary
```
after that it works. I was only looking for the process discord-canary

**Comment by crmarsh** [comment]
Yeah, I keep meaning to add a install script that does this, sorry :-/

**Comment by Lerentis** [comment]
No problem mate. Thanks that there even is a native app for Linux (:

**Comment by ahjolinna** [comment]
@Lerentis : well ...discord uses electron so it isn't a native app it's just simple (bad) webapp like skype and spotify is on linux nowdays, there is an unoffical [qdiscord](https://github.com/george99g/QDiscord) project that uses Qt5 and that's native app. unfortunately Web-apps/wrappers are just the new "fetish" after java ..thank god that shit is at least dead (in some areas).

**Comment by TheElectronWill** [comment]
@ahjolinna Well, electron-based webapps (and Java apps by the way) aren't always bad. Examples : Discord and Atom ^^. And just because an app is native doesn't mean it is better.
But let's not start a war "c/c++ apps vs less native apps".
