### ISSUE TITLE
javascript error

### ISSUE THREAD

**Issue by kessanro** [crmarsh/discord-linux-bugs#164]
it show this in a dialog box
Uncaught exception:
 TypeError: Utils.setFocused is not a function
    at launchMainAppWindow (/usr/share/discord-canary/resources/app.asar/index.js:596:11)
    at SplashWindow.<anonymous> (/usr/share/discord-canary/resources/app.asar/index.js:608:16)
    at SplashWindow.g (events.js:286:16)
    at emitNone (events.js:86:13)
    at SplashWindow.emit (events.js:185:7)
    at SplashWindow._launchMainWindow (/usr/share/discord-canary/resources/app.asar/SplashWindow.js:255:14)
    at Modules.<anonymous> (/usr/share/discord-canary/resources/app.asar/SplashWindow.js:64:15)
    at emitThree (events.js:121:20)
    at Modules.emit (events.js:194:7)
    at /usr/share/discord-canary/resources/app.asar/common/Modules.js:331:110
    at _combinedTickCallback (internal/process/next_tick.js:67:7)
    at process._tickDomainCallback (internal/process/next_tick.js:122:9)

**Comment by Rynaro** [comment]
Can you start the DiscordCanary in terminal to get some activity log information? When you do this, paste the log here. :smiley:

**Comment by kessanro** [comment]
message box
Uncaught exception:
 TypeError: Utils.setFocused is not a function
    at BrowserWindow.<anonymous> (/usr/share/discord-canary/resources/app.asar/index.js:559:13)
    at emitOne (events.js:101:20)
    at BrowserWindow.emit (events.js:188:7)
terminal
DiscordCanary 0.0.13
Gtk-Message: (for origin information, set GTK_DEBUG): failed to retrieve property `gtk-primary-button-warps-slider' of type `gboolean' from rc file value "((GString*) 0x3508cb8b2c80)" of type `gboolean'

**Comment by kessanro** [comment]
@Rynaro message box
Uncaught exception:
TypeError: Utils.setFocused is not a function
at BrowserWindow. (/usr/share/discord-canary/resources/app.asar/index.js:559:13)
at emitOne (events.js:101:20)
at BrowserWindow.emit (events.js:188:7)
terminal
DiscordCanary 0.0.13
Gtk-Message: (for origin information, set GTK_DEBUG): failed to retrieve property gtk-primary-button-warps-slider' of typegboolean' from rc file value "((GString*) 0x3508cb8b2c80)" of type `gboolean'

**Comment by Rynaro** [comment]
What are your distro version, and actual desktop environment?
I don't think it's a distro incompatibility, but this informantion can show other important informations.

**Comment by kessanro** [comment]
@Rynaro it is linux mint 18 kde plasma desktop

**Comment by kessanro** [comment]
@Rynaro here is a screenshot
![image](https://cloud.githubusercontent.com/assets/21036927/21744788/b3fba4d4-d514-11e6-9c78-256ffdfc5078.png)

**Comment by Rynaro** [comment]
Actually I use DiscordCanary in a KDE environment, but my distro is Debian Stretch actually.
I've installed DiscordCanary via `gdebi`, not using pure `dpkg`. I like to use `gdebi` because some dependencies is solved in install proccess.
Have you installed DiscordCanary via pure `dpkg`?

**Comment by kessanro** [comment]
yes @Rynaro

**Comment by Rynaro** [comment]
Try completely remove DiscordCanary from your system. Download recent version of Discord, if Discord Team releases another version.
Install the `gdebi` tool and install via `gdebi` using `sudo gdebi <package name>.deb`. If your system don`t have an specific dependency package installed, the `gdebi` tool can get for you.

**Comment by kessanro** [comment]
@Rynaro didn't work i did everything you said and didn't do anything

**Comment by Rynaro** [comment]
@kessanro I noticed a similar problem with Brackets editor in specifics versions of Linux Mint. Brackets doesn't has a Electron instances running in background like Discord, but some libraries conflicts with the CEF instance of Brackets in Mint.
I need to study the Mint particularities inside the library release of their repositories. And in the same side, I think Discord need to be more independent in your application instance to avoid this problems.
---
Can you have another applications that uses a CEF instance, like Atom? If not, install one of these applications to see how CEF will run in your Mint environment.

**Comment by MrAureliusR** [comment]
I am having the same issue on a fresh install of Ubuntu 16.04.1. It used to work fine, but since updating to .15 it crashes with the same bug as described above. Can paste the whole log, and/or screenshot of the event. As a matter of fact, here's a screenshot:
![virtualbox_rbw_29_01_2017_21_22_56](https://cloud.githubusercontent.com/assets/4911781/22410715/c9c06974-e669-11e6-8c3f-514ea714d0d6.png)

**Comment by strikerttd** [comment]
Was also running into the missing libc++.so.1 library.  Resolved on Fedora 25 by installing libcxx:

$ sudo dnf install libcxx
