### ISSUE TITLE
Multiple users cannot use Discord in the same time

### ISSUE THREAD

**Issue by valentindavid** [crmarsh/discord-linux-bugs#173]
When launching Discord by multiple users, it fails with the following error:

```
Uncaught exception:
 Error: EPERM: operation not permitted, unlink '/tmp/discordcanary.sock'
    at Error (native)
    at Object.fs.unlinkSync (fs.js:1099:18)
    at deleteSocketFile (/opt/discord/resources/app.asar/singleInstance.js:34:20)
    at listenForArgumentsFromNewProcess (/opt/discord/resources/app.asar/singleInstance.js:54:3)
    at Socket.<anonymous> (/opt/discord/resources/app.asar/singleInstance.js:105:18)
    at emitOne (events.js:96:13)
    at Socket.emit (events.js:188:7)
    at emitErrorNT (net.js:1272:8)
    at _combinedTickCallback (internal/process/next_tick.js:74:11)
    at process._tickDomainCallback (internal/process/next_tick.js:122:9)
```

**Comment by crmarsh** [comment]
Hmm, I hadn't really considered the multi user case. I guess that should be pretty easy to fix, but I am curious as an aside: you have an actual multi user system? What's your use case, you share it with a SO that way?

**Comment by OvermindDL1** [comment]
> Hmm, I hadn't really considered the multi user case. I guess that should be pretty easy to fix, but I am curious as an aside: you have an actual multi user system? What's your use case, you share it with a SO that way?

For note, my wife and I can share the same system (and indeed do pretty often over thinclients around the house to the main big computer), but I'm the only one that uses Discord (so far) but that could easily change.  This is a usage that is not rare though.  :-)

**Comment by crmarsh** [comment]
I tried to do that for a little while with my wife but it was more hassle than it was worth for us.

**Comment by OvermindDL1** [comment]
> I tried to do that for a little while with my wife but it was more hassle than it was worth for us.

We've both been using linux for a long long time, and her desktop is significantly more powerful than mine, we I often have a remote X session into her computer for web browsing and chatting while programming while she uses her session.  My phone and a chromebook (with straight linux on it) both are good for that remote connection.  It works well for us.  :-)

**Comment by crmarsh** [comment]
Cool. Well, anyway, it shouldn't be too hard to put a uid in the name or something.

**Comment by Thaodan** [comment]
why you use /tmp anyway? there's /run/user/$(id -u). Just create a socket in the dir of each user and not in tmp.
The rights to access the socket arent sane anyway:
srwxr-xr-x 1 bidar users 0  7. Mai 16:04 /tmp/discord.sock=

**Comment by OvermindDL1** [comment]
@Thaodan has a very good point I agree.

**Comment by valentindavid** [comment]
Please use XDG_RUNTIME_DIR according to Freedesktop specifications.

https://specifications.freedesktop.org/basedir-spec/basedir-spec-latest.html

**Comment by aaronfranke** [comment]
Still having this issue with the latest version of Discord.

**Comment by ScoreUnder** [comment]
That directory (`/run/user`, `/var/run/user`) does not exist on my system. With that in mind I don't think it's a good idea to use it unless a fallback is in place.

**Comment by Thaodan** [comment]
How old is your system? 
$XDG_RUNTIME_DIR is the variable and the fallback is explained here:
"If $XDG_RUNTIME_DIR is not set applications should fall back to a replacement directory 
with similar capabilities and print a warning message. Applications should use this 
directory for communication and synchronization purposes and should not place larger 
files in it, since it might reside in runtime memory and cannot necessarily be swapped out 
to disk. "

Source: https://standards.freedesktop.org/basedir-spec/basedir-spec-latest.html

I think /tmp/discord-$(id- u) is a pretty workaround.

On new systems especially when using systemd this is present.
https://serverfault.com/questions/388840/good-default-for-xdg-runtime-dir

**Comment by ScoreUnder** [comment]
It is currently up-to-date to within the last couple of days. (Gentoo)

I agree that the `id -u` workaround may be worthwhile.

**Comment by OvermindDL1** [comment]
And I just hit this myself.  My wife started using Discord too, and as we both X from the same server it is borking...

**Comment by valentindavid** [comment]
@ScoreUnder This is because you use OpenRC and not Systemd. Both are usable in Gentoo, you just have to choose (through "eselect profile"). I personally use Gentoo with Systemd. OpenRC has some limitations for desktop and Gentoo w/OpenRC should not be considered as a modern *desktop* Linux distribution. I am not sure Wayland works out of the box on OpenRC for example.

Many applications rely on XDG_RUNTIME_DIR: Gnome, KDE, PulseAudio, Wayland, etc. Many of them use workarounds for older systems. And it is a good idea. It is recommended by the Freedesktop specifications (with printing a warning though).

However, fixed names in /tmp are probably a bad idea. Other users could create those files or directories just to annoy you. You cannot delete them. It could even be a security issue if the software does not check the owner of the file. Files and directories in /tmp should have a random name. And you need to keep track of them in your home directory with a symlink. This is the way PulseAudio deals with older systems that do not have XDG_RUNTIME_DIR. I recommend to have a look at PulseAudio.

**Comment by Thaodan** [comment]
A workaround is to set these environment variables elsewhere.
These have nothing to do with systemd it's just a coincidence that systemd 
uses that too.
A way to set this is in xinit or in pam env for example.

**Comment by valentindavid** [comment]
Coincidence it is the same guy who wrote the specifications and systemd?

**Comment by crmarsh** [comment]
I'm cool with switching it to use `XDG_RUNTIME_DIR`, I just have not gotten around to working on it, and it doesn't seem super urgent. I think that for the vast majority of people using Linux on their desktop gaming machine, they are not on a multi user system so this bug would never hit them.

**Comment by OvermindDL1** [comment]
> I'm cool with switching it to use XDG_RUNTIME_DIR, I just have not gotten around to working on it, and it doesn't seem super urgent. I think that for the vast majority of people using Linux on their desktop gaming machine, they are not on a multi user system so this bug would never hit them.

:-(

**Comment by valentindavid** [comment]
For those who want, flatpak's Discord package works around the issue.

**Comment by OvermindDL1** [comment]
> For those who want, flatpak's Discord package works around the issue.

Linkie?  :-)

**Comment by valentindavid** [comment]
> Linkie? :-)

After you have installed flatpak (http://flatpak.org/getting.html), add flathub repository (https://flathub.org/), then:

```
flatpak install flathub com.discordapp.Discord
```

Source of the package if you need to report bugs: https://github.com/flathub/com.discordapp.Discord

**Comment by 132ikl** [comment]
Still an issue on Arch 0.0.2-1.
