### ISSUE TITLE
Linux Discord Canary 0.0.13 "Uncaught Exception" error during update

### ISSUE THREAD

**Issue by SapphireTactician** [crmarsh/discord-linux-bugs#174]
### Description:

While using Discord (*for Linux*) Canary version 0.0.13 tonight, I noticed a green arrow indicating that an update was ready. Upon applying the updates from within Discord, I received the following error message:

    Uncaught exception:
     Error: libc++.so.1: cannot open shared object file: No such file or directory
        at Error (native)
        at process.module.(anonymous function) [as dlopen] (ELECTRON_ASAR.js:173:20)
        at Object.Module._extensions..node (module.js:583:18)
        at Object.module.(anonymous function) [as .node] (ELECTRON_ASAR.js:173:20)
        at Module.load (module.js:473:32)
        at tryModuleLoad (module.js:432:12)
        at Function.Module._load (module.js:424:3)
        at Module.require (module.js:483:17)
        at require (internal/module.js:20:19)
        at Object.<anonymous> (/home/drew/.config/discordcanary/0.0.13/modules/discord_voice/index.js:1:98)
        at Module._compile (module.js:556:32)
        at Object.Module._extensions..js (module.js:565:10)
        at Module.load (module.js:473:32)
        at tryModuleLoad (module.js:432:12)
        at Function.Module._load (module.js:424:3)
        at Module.require (module.js:483:17)
        at require (internal/module.js:20:19)
        at Object.<anonymous> (/usr/share/discord-canary/resources/app.asar/VoiceEngine.js:7:22)
        at Module._compile (module.js:556:32)
        at Object.Module._extensions..js (module.js:565:10)
        at Module.load (module.js:473:32)
        at tryModuleLoad (module.js:432:12)
        at Function.Module._load (module.js:424:3)
        at Module.require (module.js:483:17)
        at require (internal/module.js:20:19)
        at launchMainAppWindow (/usr/share/discord-canary/resources/app.asar/index.js:477:26)
        at SplashWindow.<anonymous> (/usr/share/discord-canary/resources/app.asar/index.js:608:16)
        at SplashWindow.g (events.js:286:16)
        at emitNone (events.js:86:13)
        at SplashWindow.emit (events.js:185:7)
        at SplashWindow._launchMainWindow (/usr/share/discord-canary/resources/app.asar/SplashWindow.js:255:14)
        at Modules.<anonymous> (/usr/share/discord-canary/resources/app.asar/SplashWindow.js:64:15)
        at emitThree (events.js:121:20)
        at Modules.emit (events.js:194:7)
        at /usr/share/discord-canary/resources/app.asar/common/Modules.js:331:110
        at _combinedTickCallback (internal/process/next_tick.js:67:7)
        at process._tickDomainCallback (internal/process/next_tick.js:122:9)

Upon clicking "Okay", it hung at "Installing Updates".

Discord (*for Linux*) Canary 0.0.13 now fails to launch successfully, remaining stuck indefinitely at "Checking for Updates" when launching. Please advise. For what it's worth, the Linux distro I'm using is Debian 8 (*64-bit*).

**Comment by jdf3** [comment]
Have the same issue on Ubuntu 16.04, presumably on the automatic upgrade to 0.0.13 from 0.0.12

After 30 seconds of inspection, I can't tell the difference between the exception and call stack that I see from what @SapphireTactician provided.

**Comment by JamesShorthouse** [comment]
Same issue here, running Solus

**Comment by EVPJ** [comment]
Same issue, running GalliumOS

**Comment by Jibodeah** [comment]
Same here, Fedora 25. I did a `dnf provides` search and installed `libcxx`. After which the updater prompts me to download v0.0.14.

I've installed v0.0.14 and it works fine. So it looks like a missing dependency for `libcxx`, or whatever provides C++11 libraries on your system.

**Comment by jdf3** [comment]
I did the same as @Jibodeah. On ubuntu 16.04, libc++-dev provides this missing library.  Installing (I assume) provided the same result.

**Comment by ZallionTDE** [comment]
If that's the case, shouldn't there be a prereq check for that package? (just thinking ahead.)

**Comment by SapphireTactician** [comment]
There's a 0.0.14? You know, it'd be nice if they actually kept the changes page with the download links current... :man_facepalming:

**Comment by solacelost** [comment]
We've been on 0.0.13 for a while now, the update it failed was 0.0.14 which probably got referenced before it was available which caused the crash in _tickDomainCallack. Now that the package is available it works fine. Was a very brief interruption.

**Comment by SapphireTactician** [comment]
Closing as resolved.

**Comment by combusterf** [comment]
From the Gentoo user's point of view, this change means that I am now required to run unstable packages. While that's not a personal issue, this change will obviously reach mainstream at some point if gone unmodified.

Therefore a sanity check - what is the reason that you're not using libstdc++ instead, considering it provides the same functionality as well as essentially being mandatory on any Linux distribution, or alternatively bundling the libc++.so considering libraries are already shipped that way?

**Comment by SapphireTactician** [comment]
@combusterf I'm not experienced enough to comment on Gentoo, but as a Debian Stable user, 0.0.14 and up simply adds libc++ as a dependency which my package manager had no issues adding. I'm not sure what you mean if you're calling libc++ unstable given Debian has it, and they're probably the most anal about stability unless I'm wrong.
