### ISSUE TITLE
Javascript bug on discord 0.0.14

### ISSUE THREAD

**Issue by Nisengo** [crmarsh/discord-linux-bugs#176]
Version 0.0.13 gave me a warning that I had to upgrade to the new version available for debian derivatives. I run Linux Mint 18 Cinnamon 64bit.

version 0.0.14 errors when starting up, and 0.0.13 doesn't work anymore.

Removing old directory  0.0.13
DiscordCanary 0.0.14
[Modules] Modules initializing
[Modules] Distribution: remote
[Modules] Host updates: enabled
[Modules] Module updates: enabled
[Modules] Install path: /home/nicole/.config/discordcanary/0.0.14/modules
[Modules] Bootstrapping...
[Modules] Installing discord_rpc@1 from /usr/share/discord-canary/resources/bootstrap/discord_rpc.zip
[Modules] Installing discord_toaster@1 from /usr/share/discord-canary/resources/bootstrap/discord_toaster.zip
[Modules] Installing discord_utils@1 from /usr/share/discord-canary/resources/bootstrap/discord_utils.zip
[Modules] Installing discord_voice@1 from /usr/share/discord-canary/resources/bootstrap/discord_voice.zip
[Modules] Finished module installations. [success: 4] [failure: 0]
[Modules] Checking for host updates.
[Modules] Host is up to date.
[Modules] Checking for module updates at https://discordapp.com/api/modules/canary/versions.json
[Modules] No module updates available.
Uncaught exception:
 Error: libc++.so.1: cannot open shared object file: No such file or directory
    at Error (native)
    at process.module.(anonymous function) [as dlopen] (ELECTRON_ASAR.js:173:20)
    at Object.Module._extensions..node (module.js:583:18)
    at Object.module.(anonymous function) [as .node] (ELECTRON_ASAR.js:173:20)
    at Module.load (module.js:473:32)
    at tryModuleLoad (module.js:432:12)
    at Function.Module._load (module.js:424:3)
    at Module.require (module.js:483:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (/home/nicole/.config/discordcanary/0.0.14/modules/discord_voice/index.js:1:98)
    at Module._compile (module.js:556:32)
    at Object.Module._extensions..js (module.js:565:10)
    at Module.load (module.js:473:32)
    at tryModuleLoad (module.js:432:12)
    at Function.Module._load (module.js:424:3)
    at Module.require (module.js:483:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (/usr/share/discord-canary/resources/app.asar/VoiceEngine.js:7:22)
    at Module._compile (module.js:556:32)
    at Object.Module._extensions..js (module.js:565:10)
    at Module.load (module.js:473:32)
    at tryModuleLoad (module.js:432:12)
    at Function.Module._load (module.js:424:3)
    at Module.require (module.js:483:17)
    at require (internal/module.js:20:19)
    at launchMainAppWindow (/usr/share/discord-canary/resources/app.asar/index.js:477:26)
    at SplashWindow.<anonymous> (/usr/share/discord-canary/resources/app.asar/index.js:608:16)
    at SplashWindow.g (events.js:286:16)
    at emitNone (events.js:86:13)
    at SplashWindow.emit (events.js:185:7)
    at SplashWindow._launchMainWindow (/usr/share/discord-canary/resources/app.asar/SplashWindow.js:255:14)
    at Modules.<anonymous> (/usr/share/discord-canary/resources/app.asar/SplashWindow.js:64:15)
    at emitThree (events.js:121:20)
    at Modules.emit (events.js:194:7)
    at /usr/share/discord-canary/resources/app.asar/common/Modules.js:325:110
    at _combinedTickCallback (internal/process/next_tick.js:67:7)
    at process._tickDomainCallback (internal/process/next_tick.js:122:9)

**Comment by Nisengo** [comment]
Apparently it now requires a new dependency but it doesn't depend on it when installing with dpkg

**Comment by schoentoon** [comment]
Getting the same error on Fedora 25.

**Comment by Nisengo** [comment]
It now depends on libc++1, so install that and it works

**Comment by Jibodeah** [comment]
See #174... Although that apparently came to conclusion that it was temporary but this would seem to contradict that...

**Comment by alexandrpaliy** [comment]
Gentoo here, had exactly the same issue today. Not a bug, just point somewhere that there is new dependency.

**Comment by crmarsh** [comment]
Yeah, we added a new dependency, this is not really a bug, but I guess the upgrade process needs some work.
