### ISSUE TITLE
0.0.15 throws error, cannot open shared object file.

### ISSUE THREAD

**Issue by sustained** [crmarsh/discord-linux-bugs#177]
I haven't had any problems before but all of a sudden with 0.0.15, this happens:

```DiscordCanary 0.0.15
[Modules] Modules initializing
[Modules] Distribution: remote
[Modules] Host updates: enabled
[Modules] Module updates: enabled
[Modules] Install path: /home/sustained/.config/discordcanary/0.0.15/modules
[Modules] No updates to install
[Modules] Checking for host updates.
[Modules] Host is up to date.
[Modules] Checking for module updates at https://discordapp.com/api/modules/canary/versions.json
[Modules] No module updates available.
Uncaught exception:
 Error: libc++.so.1: cannot open shared object file: No such file or directory
    at Error (native)
    at process.module.(anonymous function) [as dlopen] (ELECTRON_ASAR.js:173:20)
    at Object.Module._extensions..node (module.js:583:18)
    at Object.module.(anonymous function) [as .node] (ELECTRON_ASAR.js:173:20)
    at Module.load (module.js:473:32)
    at tryModuleLoad (module.js:432:12)
    at Function.Module._load (module.js:424:3)
    at Module.require (module.js:483:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (/home/sustained/.config/discordcanary/0.0.15/modules/discord_voice/index.js:1:98)
    at Module._compile (module.js:556:32)
    at Object.Module._extensions..js (module.js:565:10)
    at Module.load (module.js:473:32)
    at tryModuleLoad (module.js:432:12)
    at Function.Module._load (module.js:424:3)
    at Module.require (module.js:483:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (/home/sustained/Hämtningar/DiscordCanary/resources/app.asar/VoiceEngine.js:7:22)
    at Module._compile (module.js:556:32)
    at Object.Module._extensions..js (module.js:565:10)
    at Module.load (module.js:473:32)
    at tryModuleLoad (module.js:432:12)
    at Function.Module._load (module.js:424:3)
    at Module.require (module.js:483:17)
    at require (internal/module.js:20:19)
    at launchMainAppWindow (/home/sustained/Hämtningar/DiscordCanary/resources/app.asar/index.js:477:26)
    at SplashWindow.<anonymous> (/home/sustained/Hämtningar/DiscordCanary/resources/app.asar/index.js:608:16)
    at SplashWindow.g (events.js:286:16)
    at emitNone (events.js:86:13)
    at SplashWindow.emit (events.js:185:7)
    at SplashWindow._launchMainWindow (/home/sustained/Hämtningar/DiscordCanary/resources/app.asar/SplashWindow.js:255:14)
    at Modules.<anonymous> (/home/sustained/Hämtningar/DiscordCanary/resources/app.asar/SplashWindow.js:64:15)
    at emitThree (events.js:121:20)
    at Modules.emit (events.js:194:7)
    at /home/sustained/Hämtningar/DiscordCanary/resources/app.asar/common/Modules.js:325:110
    at _combinedTickCallback (internal/process/next_tick.js:67:7)
    at process._tickDomainCallback (internal/process/next_tick.js:122:9)
```

**Comment by ahjolinna** [comment]
@sustained : do u have libc++ installed?

**Comment by sustained** [comment]
Sorry, I had just woken up and was half asleep and so didn't even think to search existing issues.

I couldn't find `libc++` in the Fedora repos, however installing `libcxx` did the trick.

**Comment by ahjolinna** [comment]
well libc++ is same as libcxx, I do wonder why fedora uses that name instead...sigh..but who cares

**Comment by joserobjr** [comment]
I'm also having this issue, which package contains libc++ on OpenSUSE? I tried libcxx-gtk-utils-3-2_2-0, libcxx-gtk-utils-3-devel, libcxxtools9 but it still crashes...

**Comment by joserobjr** [comment]
The non-canary version worked! I'm happy to see that the linux version is on the main site now :D
https://dl.discordapp.net/apps/linux/0.0.1/discord-0.0.1.tar.gz

**Comment by ahjolinna** [comment]
@joserobjr : the stable version doesn't yet require libc++, anyway about openSUSE have you check/installed: https://software.opensuse.org/package/libc++1 ?

PS. there are some that maintain discord stable version for opensuse: https://software.opensuse.org/package/discord
