### ISSUE TITLE
Blank screen, Cannot find 'discord_utils'

### ISSUE THREAD

**Issue by lakeman** [crmarsh/discord-linux-bugs#178]
[Ctrl + Shift + I]
```
Uncaught Error: Cannot find module 'discord_utils'
Error: Cannot find module 'discord_utils'
    at Function.Module._resolveFilename (module.js:339:15)
    at Function.Module._load (module.js:290:25)
    at Module.require (module.js:367:17)
    at EventEmitter.<anonymous> (/usr/share/discord-canary/resources/electron.asar/browser/rpc-server.js:243:70)
    at emitTwo (events.js:100:13)
    at EventEmitter.emit (events.js:185:7)
    at EventEmitter.<anonymous> (/usr/share/discord-canary/resources/electron.asar/browser/api/web-contents.js:139:25)
    at emitTwo (events.js:100:13)
    at EventEmitter.emit (events.js:185:7)
```

Tried uninstall / kill / install / start. Hasn't changed anything...

**Comment by aalong** [comment]
Can confirm, same issue on Ubuntu 16.04. The window is solid gray, nothing I'm able to interact with helps, and the same console error displays.

**Comment by crmarsh** [comment]
Oh, now I understand where these bugs are coming from. I thought everyone was on latest.
