### ISSUE TITLE
Discord not opening

### ISSUE THREAD

**Issue by bubbadoobop** [crmarsh/discord-linux-bugs#217]
# Fixed!

I managed to fix this issue by installing [libc++/libc++1](https://libcxx.llvm.org/) from the AUR. **NOTE:** In order to install libc++ (on the AUR), you have to import it's GPG keys. which can be done using the command
```
gpg --recv-keys <KEYID - See 'validpgpkeys' array in PKGBUILD>
```
To find the keys, see line 24 (validgpgkeys) in the [PKGBUILD](https://aur.archlinux.org/cgit/aur.git/tree/PKGBUILD?h=libc%2B%2B).

However, you may get a general server error in your terminal feedback when you run the command. To combat this, I would suggest using a more specific command to import your key
```
gpg --keyserver <server URL> --recv <keyID, usually a string of random alphanumeric characters>
```
After that, you should be able to easily to reinstall Discord and get rolling again. 

Thanks to @pnaf and @wwwg, and to @crmarsh for letting everyone know why libc++ wasn't in the dependencies. 
___

# Initial Error Report
I've been getting a window that details an update available for Discord. My client is updated. When I try to run discord, I get a blank window. 

![Blank Window](https://raw.githubusercontent.com/bubbadoobop/issue-screenshots/master/Screenshot_20170808_221926.png) 

When I try to open it in terminal, I get this message...

```
[ian@replicant Discord]$ ./Discord
Removing old directory  0.0.1
Discord 0.0.2
[Modules] Modules initializing
[Modules] Distribution: remote
[Modules] Host updates: enabled
[Modules] Module updates: enabled
[Modules] Install path: /home/ian/.config/discord/0.0.2/modules
[Modules] Bootstrapping...
[Modules] Installing discord_rpc@1 from /home/ian/Downloads/Discord/resources/bootstrap/discord_rpc.zip
[Modules] Installing discord_toaster@1 from /home/ian/Downloads/Discord/resources/bootstrap/discord_toaster.zip
[Modules] Installing discord_utils@1 from /home/ian/Downloads/Discord/resources/bootstrap/discord_utils.zip
[Modules] Installing discord_voice@1 from /home/ian/Downloads/Discord/resources/bootstrap/discord_voice.zip
[Modules] Finished module installations. [success: 4] [failure: 0]
[Modules] Checking for host updates.
[Modules] Host is up to date.
[Modules] Checking for module updates at https://discordapp.com/api/modules/stable/versions.json
[Modules] No module updates available.
```

**EDIT:** I forgot to say this but I'm on Manjaro 17.0.2, incase if anyone is interested.

**Comment by yochaigal** [comment]
Same for me after updating to 0.0.2 on Arch Linux. Interestingly, going back to 1.0 doesn't solve the issue, even after deleting all local discord caches and config.

**Comment by pnaf** [comment]
I'm also encountering this issue on both Debian 9 and Ubuntu 16.04 LTS.

Output of developer console [Shift+Ctrl+I]:

```
Uncaught Error: libc++.so.1: cannot open shared object file: No such file or directory
    at process.module.(anonymous function) [as dlopen] (ELECTRON_ASAR.js:173:20)
    at Object.Module._extensions..node (module.js:598:18)
    at Object.module.(anonymous function) [as .node] (ELECTRON_ASAR.js:173:20)
    at Module.load (module.js:488:32)
    at tryModuleLoad (module.js:447:12)
    at Function.Module._load (module.js:439:3)
    at Module.require (module.js:498:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (/home/[...]/.config/discord/0.0.2/modules/discord_voice/index.js:1:176)
    at Object.<anonymous> (/home/[...]/.config/discord/0.0.2/modules/discord_voice/index.js:60:3)
    at Module._compile (module.js:571:32)
    at Object.Module._extensions..js (module.js:580:10)
    at Module.load (module.js:488:32)
    at tryModuleLoad (module.js:447:12)
    at Function.Module._load (module.js:439:3)
    at Module.require (module.js:498:17)
    at require (internal/module.js:20:19)
    at Object.require (https://discordapp.com/assets/43eee699267e37d87126.js:1:1480925)
    at Object.getVoiceEngine (https://discordapp.com/assets/43eee699267e37d87126.js:1:1482921)
    at Object.getDiscordUtils (https://discordapp.com/assets/43eee699267e37d87126.js:1:1483014)
    at Object.setObservedGamesCallback (https://discordapp.com/assets/43eee699267e37d87126.js:1:1482316)
    at Object.<anonymous> (https://discordapp.com/assets/43eee699267e37d87126.js:1:523252)
    at t (https://discordapp.com/assets/7616f527ada5a8b21f31.js:1:101)
    at Object.<anonymous> (https://discordapp.com/assets/43eee699267e37d87126.js:1:296128)
    at t (https://discordapp.com/assets/7616f527ada5a8b21f31.js:1:101)
    at Object.<anonymous> (https://discordapp.com/assets/43eee699267e37d87126.js:1:2652720)
    at t (https://discordapp.com/assets/7616f527ada5a8b21f31.js:1:101)
    at window.webpackJsonp (https://discordapp.com/assets/7616f527ada5a8b21f31.js:1:418)
    at https://discordapp.com/assets/43eee699267e37d87126.js:1:1
```

**Comment by pnaf** [comment]
I was using the Discord 0.0.2 tarball, so the workaround for me was installing **libc++1**. The official .deb already includes this dependency.

**Comment by wwwg** [comment]
I also had this issue on Manjaro 17.0.2, I fixed by installing libc++ from the AUR.

**Comment by crmarsh** [comment]
Yeah, we require libc++. The .deb version has it as a dep, but (obviously) there was no way to add that to the tar. In previous versions this would have crashed the main process (which is much more obvious), so I guess this is a regression in that sense :-/

**Comment by ahjolinna** [comment]
I really don't get why there can't be any dependency "list" somewhere ..it's not that hard 

in Arch it's : "gtk2 libnotify libxss glibc alsa-lib libpng nspr nss libpulse libc++"

yes pkgs naming do vary between different distros...at time a lot ...and some in a weird ways... its still better than nothing

**Comment by TehFreek** [comment]
The relevant package for Fedora is `libcxx`.

**Comment by aaronfranke** [comment]
Confirmed that `sudo apt install libc++1` fixes the issue. This should be listed as a dependency for Discord when it's distributed as a .deb package.

**Comment by andrewschott** [comment]
@crmarsh I would be happy to package this up for you, or at minimal offer a spec file.  Could you provide me the dependencies so I can have a guaranteed to work package?

Thanks!

**Comment by aaronfranke** [comment]
Hold up, has this dependency been added? The fact that a work-around exists (installing the package manually) doesn't mean you should close this bug report.

**Comment by haugsvar** [comment]
This did the trick for me on opensuse leap 42.2:

`zypper in llvm- llvm-devel llvm-clang llvm-clang-devel; depmod -a`

**Comment by bubbadoobop** [comment]
I'll reopen the issue (by request of @aaronfranke). He brought up a pretty good point.

**Comment by AMonreale** [comment]
Installing libcxx on Fedora worked.

@crmarsh you could just add a readme file with instructions of how to install the required dependencies.
