### ISSUE TITLE
Failed start: uncaught error

### ISSUE THREAD

**Issue by darthazad** [crmarsh/discord-linux-bugs#218]
`Uncaught Error: /home/dar/.config/discord/0.0.2/modules/discord_voice/discord_voice.node: undefined symbol: _ZNSt3__119__shared_weak_countD2Ev
    at process.module.(anonymous function) [as dlopen] (ELECTRON_ASAR.js:173:20)
    at Object.Module._extensions..node (module.js:598:18)
    at Object.module.(anonymous function) [as .node] (ELECTRON_ASAR.js:173:20)
    at Module.load (module.js:488:32)
    at tryModuleLoad (module.js:447:12)
    at Function.Module._load (module.js:439:3)
    at Module.require (module.js:498:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (/home/dar/.config/discord/0.0.2/modules/discord_voice/index.js:1:176)
    at Object.<anonymous> (/home/dar/.config/discord/0.0.2/modules/discord_voice/index.js:60:3)
    at Module._compile (module.js:571:32)
    at Object.Module._extensions..js (module.js:580:10)
    at Module.load (module.js:488:32)
    at tryModuleLoad (module.js:447:12)
    at Function.Module._load (module.js:439:3)
    at Module.require (module.js:498:17)
    at require (internal/module.js:20:19)
    at Object.require (https://discordapp.com/assets/43eee699267e37d87126.js:1:1480925)
    at Object.getVoiceEngine (https://discordapp.com/assets/43eee699267e37d87126.js:1:1482921)
    at Object.getDiscordUtils (https://discordapp.com/assets/43eee699267e37d87126.js:1:1483014)
    at Object.setObservedGamesCallback (https://discordapp.com/assets/43eee699267e37d87126.js:1:1482316)
    at Object.<anonymous> (https://discordapp.com/assets/43eee699267e37d87126.js:1:523252)
    at t (https://discordapp.com/assets/7616f527ada5a8b21f31.js:1:101)
    at Object.<anonymous> (https://discordapp.com/assets/43eee699267e37d87126.js:1:296128)
    at t (https://discordapp.com/assets/7616f527ada5a8b21f31.js:1:101)
    at Object.<anonymous> (https://discordapp.com/assets/43eee699267e37d87126.js:1:2652720)
    at t (https://discordapp.com/assets/7616f527ada5a8b21f31.js:1:101)
    at window.webpackJsonp (https://discordapp.com/assets/7616f527ada5a8b21f31.js:1:418)
    at https://discordapp.com/assets/43eee699267e37d87126.js:1:1`

I am using fedora 21, I have tried 0.0.2, PTB and canary 0.0.24 and all start with a grey black screen and this error.

**Comment by darthazad** [comment]
You can close this, I've solved it. Basically it was my old OS using old libraries. I ended up finding RPM packages: libcxxabi-3.8.0-3.fc24.x86_64.rpm and libcxx-3.8.0-6.fc24.x86_64.rpm and installing those. They are for FC 24, not the 21 that I have, but they seem to be working.
