### ISSUE TITLE
Uncaught exception:  Error: EPERM: operation not permitted, unlink '/tmp/discordcanary.sock'

### ISSUE THREAD

**Issue by hevanaa** [crmarsh/discord-linux-bugs#223]
When another user is logged in and started discord, switching users and trying to start discord with another user account causes the following exception.

The reason is clear, because /tmp/discordcanary.sock is owned by the other user.

This also happens if the other user session crashed (either discord or their complete session/X11/battery empty/whatever) and /tmp/discordcanary.sock is left, owned by the other user.

This should be fixed so that clients running under different users do not interfere with each other, preferably not using the same socket in /tmp.

> A JavaScript error occurred in the main process
> 
> Uncaught exception:
>  Error: EPERM: operation not permitted, unlink '/tmp/discordcanary.sock'
>     at Object.fs.unlinkSync (fs.js:1007:18)
>     at deleteSocketFile (/opt/DiscordCanary/resources/app.asar/singleInstance.js:34:20)
>     at listenForArgumentsFromNewProcess (/opt/DiscordCanary/resources/app.asar/singleInstance.js:54:3)
>     at Socket.<anonymous> (/opt/DiscordCanary/resources/app.asar/singleInstance.js:105:18)
>     at emitOne (events.js:96:13)
>     at Socket.emit (events.js:188:7)
>     at emitErrorNT (net.js:1281:8)
>     at _combinedTickCallback (internal/process/next_tick.js:74:11)
>     at process._tickDomainCallback (internal/process/next_tick.js:122:9)

**Comment by oDrongo** [comment]
sudo dpkg -r discord. After, sudo apt install libc++1, and reinstall. I fixed the problem like this.

**Comment by hevanaa** [comment]
The problem can only be fixed by rewriting the software to use another location for the socket.

I'm no expert, but I believe putting a socket in /tmp is a potential security issue. Multiple CVEs have been reported for software with sockets in /tmp, among them X11.

For unprivileged software, it is recommended to use a subdirectory in $XDG_RUNTIME_DIR, see http://0pointer.net/blog/projects/tmp.html. This would fix this bug right away.
