### ISSUE TITLE
Blank screen?

### ISSUE THREAD

**Issue by LickTheCheese** [crmarsh/discord-linux-bugs#230]
when i open Discord in my Browser, it works fine but when i open Discord on my computer, it has a blank screen that says:

  
 ```
 ELECTRON_ASAR.js:173 Uncaught Error: libc++.so.1: cannot open shared object file: No such file or directory
    at process.module.(anonymous function) [as dlopen] (ELECTRON_ASAR.js:173:20)
    at Object.Module._extensions..node (module.js:598:18)
    at Object.module.(anonymous function) [as .node] (ELECTRON_ASAR.js:173:20)
    at Module.load (module.js:488:32)
    at tryModuleLoad (module.js:447:12)
    at Function.Module._load (module.js:439:3)
    at Module.require (module.js:498:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (/home/owen/.config/discord/0.0.2/modules/discord_voice/index.js:1:176)
    at Object.<anonymous> (/home/owen/.config/discord/0.0.2/modules/discord_voice/index.js:60:3)
    at Module._compile (module.js:571:32)
    at Object.Module._extensions..js (module.js:580:10)
    at Module.load (module.js:488:32)
    at tryModuleLoad (module.js:447:12)
    at Function.Module._load (module.js:439:3)
    at Module.require (module.js:498:17)
    at require (internal/module.js:20:19)
    at Object.require (https://discordapp.com/assets/4f0dcf9ebaacd43148f0.js:1:1543850)
    at Object.getVoiceEngine (https://discordapp.com/assets/4f0dcf9ebaacd43148f0.js:1:1545944)
    at Object.getDiscordUtils (https://discordapp.com/assets/4f0dcf9ebaacd43148f0.js:1:1546037)
    at Object.setObservedGamesCallback (https://discordapp.com/assets/4f0dcf9ebaacd43148f0.js:1:1545339)
    at Object.<anonymous> (https://discordapp.com/assets/4f0dcf9ebaacd43148f0.js:1:436951)
    at t (https://discordapp.com/assets/d64a34666335edfb0c62.js:1:101)
    at Object.<anonymous> (https://discordapp.com/assets/4f0dcf9ebaacd43148f0.js:1:307872)
    at t (https://discordapp.com/assets/d64a34666335edfb0c62.js:1:101)
    at Object.<anonymous> (https://discordapp.com/assets/4f0dcf9ebaacd43148f0.js:1:2748503)
    at t (https://discordapp.com/assets/d64a34666335edfb0c62.js:1:101)
    at window.webpackJsonp (https://discordapp.com/assets/d64a34666335edfb0c62.js:1:418)
    at https://discordapp.com/assets/4f0dcf9ebaacd43148f0.js:1:1




```

**Comment by mglennon** [comment]
I receive a blank Discord screen.

```
matthew@haunted-linux:~$ discord
Discord 0.0.2
[Modules] Modules initializing
[Modules] Distribution: remote
[Modules] Host updates: enabled
[Modules] Module updates: enabled
[Modules] Install path: /home/matthew/.config/discord/0.0.2/modules
[Modules] No updates to install
[Modules] Checking for host updates.
[Modules] Host is up to date.
[Modules] Checking for module updates at https://discordapp.com/api/modules/stable/versions.json
[Modules] No module updates available.
```
Ubuntu 17.04, 64-bit
```
matthew@haunted-linux:~$ uname -a
Linux haunted-linux 4.10.0-33-generic #37-Ubuntu SMP Fri Aug 11 10:55:28 UTC 2017 x86_64 x86_64 x86_64 GNU/Linux
```

**Comment by LickTheCheese** [comment]
me two

**Comment by sfirfi** [comment]
Try to Install Libc++

**Comment by LickTheCheese** [comment]
how am i supposed to know if i have that installed?

**Comment by LickTheCheese** [comment]
i tried to install it but it said:
`username@hostname:~ $ sudo aptitude show Libc++`
`E: Unable to locate package Libc++  `

**Comment by OvermindDL1** [comment]
@LickTheCheese `Libc++` != `libc++`

If on an ubuntu based OS you probably want `libc++1` anyway.

**Comment by LickTheCheese** [comment]
OK i will try that, but im in a Debian biased OS, not in Ubuntu Biased OS

**Comment by druz320** [comment]
I had the same issue on Fedora 26, installing `libcxx` solved it.

**Comment by rosycheer** [comment]
@sfirfi  thank you. i've install libc++1 (ubuntu 14.04.5, discord 0.0.2) it was helpful. thanks a lot )

**Comment by FoxCrafter** [comment]
Thank you guys! It really needed libcxx

**Comment by LickTheCheese** [comment]
thx!
