### ISSUE TITLE
I got this bugs

### ISSUE THREAD

**Issue by eav1** [crmarsh/discord-linux-bugs#64]
Uncaught Exception:
Error: EROFS: read-only file system, unlink '/tmp/discordcanary.sock'
    at Error (native)
    at Object.fs.unlinkSync (fs.js:990:18)
    at deleteSocketFile (/usr/share/discord-canary/resources/app.asar/app/singleInstance.js:34:20)
    at listenForArgumentsFromNewProcess (/usr/share/discord-canary/resources/app.asar/app/singleInstance.js:54:3)
    at Socket.<anonymous> (/usr/share/discord-canary/resources/app.asar/app/singleInstance.js:105:18)
    at emitOne (events.js:90:13)
    at Socket.emit (events.js:182:7)
    at emitErrorNT (net.js:1253:8)
    at _combinedTickCallback (internal/process/next_tick.js:74:11)
    at process._tickCallback (internal/process/next_tick.js:98:9)

**Comment by crmarsh** [comment]
You have /tmp on a read-only file system?

**Comment by eav1** [comment]
No. I am running it at a Opensuse 13.2

**Comment by crmarsh** [comment]
Does this still happen for you, I have yet to repro.

**Comment by eav1** [comment]
I changed to Opensuse leap 42.1 and I must say it stopped to happen on leap

2016-11-10 20:09 GMT-02:00 Chris Marsh <notifications@github.com>:

**Comment by circleous** [comment]
Bring this up now, same error after accidentally run Discord Canary with sudo and force closed while random click on guild channel. Simple fix is, kill DiscordCanary, remove /tmp/discordcanary.sock and restart.
